export const GET_CONTACTS ='GET_CONTACTS';
export const LOAD_CONTACTS ='LOAD_CONTACTS';
export const ADD_CONTACTS ='ADD_CONTACTS';
export const FAIL_CONTACTS ='FAIL_CONTACTS';
export const EDIT_CONTACTS ='EDIT_CONTACTS';
export const GET_ONE_CONTACT ='GET_ONE_CONTACT';